#!/usr/bin/env python3
# /// script
# requires-python = ">=3.9"
# ///
# Copyright 2026 Exabeam, Inc.
# SPDX-License-Identifier: Apache-2.0
"""Generate every artifact that carries the plugin's identity from ONE source: plugin/identity.json.

    python3 plugin/gen_identity.py            # (re)write the artifacts
    python3 plugin/gen_identity.py --check    # exit 1 if any committed artifact differs (CI)

Generated:
  .claude-plugin/plugin.json                    Claude Code manifest
  .codex-plugin/plugin.json                     Codex manifest (same skills, Codex-only fields)
  skills/soc-investigate/settings.snippet.json  the permission gate — every rule spelled out under the
                                                bundled-MCP prefix mcp__plugin_<name>_<server>__ and/or the
                                                manual prefix mcp__<server>__, from the bare-name tiers in
                                                skills/soc-investigate/permissions.json
  identity.sh                                   the same identity as shell variables, sourced by install.sh
                                                and preflight.sh — so a host with no python3 still installs
                                                the right plugin from the right marketplace (a literal
                                                fallback in the scripts would install the UPSTREAM plugin
                                                after a re-key; found in review)

`mcpServer` is cross-checked, not consumed: it must equal permissions.json's `server` and the one server
key in .mcp.json / .mcp.codex.json, so an edit to any of the three that is not mirrored fails --check.

Why: `name` is load-bearing. It is the plugin key, and Claude Code namespaces the skills (`<name>:<skill>`)
and the bundled MCP (`mcp__plugin_<name>_<server>__<tool>`) with it — which is what the permission rules
match on. Before this file, re-keying the plugin meant editing two manifests and 92 rules by hand and
hoping nothing drifted; now it is one field here plus a regenerate, and CI fails on drift. A vendor
catalog that ships this payload under its own name (see the Exabeam marketplace) patches identity.json
and regenerates — nothing else in the payload is touched.

Stdlib only; the payload ships this file, so an installed copy can regenerate itself.
"""
import json
import re
import shlex
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
IDENTITY = HERE / "identity.json"
PERMISSIONS = HERE / "skills" / "soc-investigate" / "permissions.json"
OUT = {
    "claude": HERE / ".claude-plugin" / "plugin.json",
    "codex": HERE / ".codex-plugin" / "plugin.json",
    "snippet": HERE / "skills" / "soc-investigate" / "settings.snippet.json",
    "shell": HERE / "identity.sh",
}
MCP_FILES = (".mcp.json", ".mcp.codex.json")


def load(p):
    d = json.loads(p.read_text())
    d.pop("_comment", None)
    return d


def prefixes(identity, server):
    return {"plugin": f"mcp__plugin_{identity['name']}_{server}__", "manual": f"mcp__{server}__"}


def server_keys():
    """The MCP server key(s) the shipped .mcp*.json files declare."""
    keys = set()
    for f in MCP_FILES:
        p = HERE / f
        if p.is_file():
            d = json.loads(p.read_text())
            d = d.get("mcpServers", d)
            keys |= {k for k in d if not k.startswith("_")}
    return keys


def check_server(identity, perms):
    got = {perms["server"]} | server_keys()
    if got != {identity["mcpServer"]}:
        sys.exit(f"identity.json mcpServer={identity['mcpServer']!r} does not match permissions.json server "
                 f"/ the .mcp*.json server key ({sorted(got)}) — the three must agree; nothing was written")


def shell_include(identity, perms):
    lines = ["# Copyright 2026 Exabeam, Inc.", f"# SPDX-License-Identifier: {identity['license']}",
             "# GENERATED by gen_identity.py from identity.json — do not edit; CI fails if this drifts.",
             "# Sourced by install.sh and preflight.sh so the identity is read without python3.",
             f"SOCXEN_ID_NAME={shlex.quote(identity['name'])}",
             f"SOCXEN_ID_VERSION={shlex.quote(identity['version'])}",
             f"SOCXEN_ID_LICENSE={shlex.quote(identity['license'])}",
             f"SOCXEN_ID_MCP_SERVER={shlex.quote(perms['server'])}",
             f"SOCXEN_ID_MARKETPLACE_REPO={shlex.quote(identity['marketplace']['repo'])}",
             f"SOCXEN_ID_MARKETPLACE_NAME={shlex.quote(identity['marketplace']['name'])}"]
    return "\n".join(lines) + "\n"


DOC_GLOBS = ("README.md", "docs/**/*.md", "skills/**/*.md")      # prose: rewritten on a re-key
SHELL_FILES = ("install.sh", "preflight.sh")                        # take their identity from identity.sh —
                                                                    # never rewritten; a literal key fails --check


def previous_identity():
    """The identity the shipped prose was last generated for: the committed identity.sh (#180).
    A vendor catalog re-keys the plugin by patching identity.json and regenerating; the guides then
    still name the previous distribution's install key. Reading the previous key from identity.sh lets
    the generator rewrite exactly that key (and the marketplace repo) in the prose — a no-op for the
    distribution that wrote it, a clean rename for a re-keyed copy, and reproducible from a fresh export."""
    sh = OUT["shell"]
    if not sh.exists():
        return None
    vals = {}
    for line in sh.read_text().splitlines():
        if line.startswith("SOCXEN_ID_") and "=" in line:
            k, v = line.split("=", 1)
            vals[k] = shlex.split(v)[0] if v else ""
    if not all(k in vals for k in ("SOCXEN_ID_NAME", "SOCXEN_ID_MARKETPLACE_REPO", "SOCXEN_ID_MARKETPLACE_NAME")):
        return None
    return {"key": f"{vals['SOCXEN_ID_NAME']}@{vals['SOCXEN_ID_MARKETPLACE_NAME']}", "repo": vals["SOCXEN_ID_MARKETPLACE_REPO"],
            "license": vals.get("SOCXEN_ID_LICENSE", "")}      # absent in copies generated before the license followed


def install_key(identity):
    return f"{identity['name']}@{identity['marketplace']['name']}"


def doc_files():
    seen = set()
    for g in DOC_GLOBS:
        for f in sorted(HERE.glob(g)):
            if f.is_file() and f not in seen and f != OUT["shell"]:
                seen.add(f); yield f


_AFTER = r"[A-Za-z0-9_-]"      # a character that continues an identifier: the previous key or repo followed by
_BEFORE = r"[A-Za-z0-9_]"      # one is a longer, different name (`…-dev`) and is not ours to rewrite. A leading
                               # hyphen is allowed: the shell's `${VAR:-default}` puts one right before a default.


def _replace_bounded(text, subs):
    """Exact-string replacement at identifier boundaries. Returns (text, lines) — the 1-based lines where an
    occurrence survived because it continues into a longer identifier."""
    kept = []
    for a, b in subs:
        text = re.sub(rf"(?<!{_BEFORE}){re.escape(a)}(?!{_AFTER})", lambda _m, b=b: b, text)
        kept += [text.count("\n", 0, m.start()) + 1 for m in re.finditer(re.escape(a), text)]
    return text, kept


def rewrite_docs(prev, identity):
    """Replace the previous install key and marketplace repo with the current ones in the shipped prose
    and the shell fallbacks. Exact strings at identifier boundaries; nothing else in the prose is touched.
    An occurrence that continues into a longer identifier (`socxen@open-agent-ai-security-dev`) names
    something else and is left alone — and reported, so the maintainer sees what did not move."""
    subs = [(prev["key"], install_key(identity)), (prev["repo"], identity["marketplace"]["repo"])]
    subs = [(a, b) for a, b in subs if a and a != b]
    changed, kept = [], []
    for f in doc_files():
        text = f.read_text()
        new, lines = _replace_bounded(text, subs)
        kept += [f"{f.relative_to(HERE.parent)}:{n}" for n in lines]
        if new != text:
            f.write_text(new); changed.append(f)
    return changed, kept


# An SPDX header line anywhere in the payload: an SPDX-shaped identifier (letters, digits, . + -), optionally
# closed by a comment terminator. The shape matters: this generator's own source spells the tag in code.
SPDX_RE = re.compile(r"(?m)^(?P<lead>.*SPDX-License-Identifier:[ \t]*)(?P<id>[A-Za-z0-9.+-]+)(?P<tail>[ \t]*(?:-->|\*/)?[ \t]*)$")


def badge_slug(license_id):
    """The license as the README's shields.io badge path spells it: '-' separates the badge's own fields,
    so the identifier's hyphens become underscores (rendered as spaces)."""
    return license_id.replace("-", "_")


def payload_files():
    for f in sorted(HERE.rglob("*")):
        if f.is_file() and "__pycache__" not in f.parts:
            yield f


def spdx_headers():
    """(file, identifier) for every SPDX header line in the payload."""
    for f in payload_files():
        try:
            text = f.read_text()
        except (UnicodeDecodeError, OSError):
            continue
        for m in SPDX_RE.finditer(text):
            yield f, m.group("id")


def rewrite_license(prev_license, identity):
    """A re-key may also relicense the copy: a vendor catalog serving the payload under its own terms sets
    `license` in identity.json (the manifests already follow it). Then every SPDX header in the payload
    and the README's license badge and License section follow too, so an installed copy says one thing
    about its terms in every file, and a license scanner reads the same answer its LICENSE file gives.
    The README is the only prose touched, and only where it names the identifier as THIS copy's license
    (the badge, the License section) — the invariant tests pin that those are its only mentions. The
    LICENSE / NOTICE texts are not the generator's to write; a catalog overlays them as whole files."""
    new = identity["license"]
    if not prev_license or prev_license == new:
        return []
    changed = []
    for f in payload_files():
        try:
            text = f.read_text()
        except (UnicodeDecodeError, OSError):
            continue
        out = SPDX_RE.sub(lambda m: m.group("lead") + (new if m.group("id") == prev_license else m.group("id"))
                          + m.group("tail"), text)
        if f == HERE / "README.md":
            out, _ = _replace_bounded(out, [(prev_license, new)])
            out = out.replace(f"badge/license-{badge_slug(prev_license)}-", f"badge/license-{badge_slug(new)}-")
        if out != text:
            f.write_text(out); changed.append(f)
    return changed


def build(identity, perms):
    common = {k: identity[k] for k in ("name", "version", "description", "author", "homepage", "repository", "license")}
    claude = {**common, "keywords": identity["keywords"] + identity["hostKeywords"]["claude"], "skills": "./skills/"}
    # The bundled PreToolUse hook (gate/bundled-hook, #148) is declared here when it ships in the tree, so a
    # regeneration can never silently unregister the gate and --check stays green in either merge order.
    if (HERE / "hooks" / "hooks.json").is_file():
        claude["hooks"] = "./hooks/hooks.json"
    codex = {**common, "keywords": identity["keywords"] + identity["hostKeywords"]["codex"], "skills": "./skills/",
             "mcpServers": "./.mcp.codex.json",
             "interface": {"displayName": identity["displayName"], "shortDescription": identity["shortDescription"],
                           "category": identity["category"]}}
    pre = prefixes(identity, perms["server"])
    tiers = {}
    for tier, spec in perms["tiers"].items():
        tiers[tier] = [pre[p] + t for p in spec["prefixes"] for t in spec["tools"]]
    snippet = {"permissions": tiers}
    return {"claude": claude, "codex": codex, "snippet": snippet, "shell": shell_include(identity, perms)}


def render(obj):
    return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"


def main(argv):
    check = "--check" in argv
    identity, perms = load(IDENTITY), load(PERMISSIONS)
    check_server(identity, perms)
    want = {k: (v if isinstance(v, str) else render(v)) for k, v in build(identity, perms).items()}
    stale = [k for k, text in want.items() if (OUT[k].read_text() if OUT[k].exists() else "") != text]
    prev = previous_identity()
    if check:
        names = [str(OUT[k].relative_to(HERE.parent)) for k in stale]
        guide = HERE / "docs" / "installation.md"
        if guide.exists() and install_key(identity) not in guide.read_text():
            names.append(str(guide.relative_to(HERE.parent)) + " (does not name this distribution's install key)")
        lic = identity["license"]
        wrong = sorted({str(f.relative_to(HERE.parent)) for f, i in spdx_headers() if i != lic})
        if wrong:
            names.append(f"{len(wrong)} file(s) whose SPDX header does not name this distribution's license "
                         f"{lic!r}: {', '.join(wrong[:4])}{', …' if len(wrong) > 4 else ''}")
        readme = HERE / "README.md"
        if readme.exists() and (lic not in readme.read_text() or f"badge/license-{badge_slug(lic)}-" not in readme.read_text()):
            names.append("plugin/README.md (does not name this distribution's license)")
        key = install_key(identity)
        literal = [f for f in SHELL_FILES if (HERE / f).is_file()
                   and re.search(rf"(?<!{_BEFORE}){re.escape(key)}(?!{_AFTER})", (HERE / f).read_text())]
        if literal:
            names.append(", ".join(f"plugin/{f}" for f in literal) + " (carries the install key as a literal — the shell "
                         "scripts read the identity from identity.sh; a literal is what a re-key would leave behind)")
        if names:
            print("stale (run python3 plugin/gen_identity.py): " + ", ".join(names), file=sys.stderr)
            return 1
        print(f"identity artifacts in sync with plugin/identity.json (name={identity['name']!r}, "
              f"prefix={prefixes(identity, perms['server'])['plugin']!r})")
        return 0
    changed, kept = rewrite_docs(prev, identity) if prev else ([], [])   # before identity.sh is rewritten below
    relicensed = rewrite_license(prev["license"], identity) if prev else []
    for k, text in want.items():
        OUT[k].write_text(text)
    n = sum(len(v) for v in json.loads(want["snippet"])["permissions"].values())
    print(f"wrote {', '.join(str(OUT[k].relative_to(HERE.parent)) for k in OUT)} — name={identity['name']!r}, "
          f"version {identity['version']}, {n} permission rules"
          + (f"; install key {prev['key']} → {install_key(identity)} in {len(changed)} file(s)" if changed else "")
          + (f"; left {len(kept)} longer identifier(s) untouched: {', '.join(kept)}" if kept else "")
          + (f"; license {prev['license']} → {identity['license']} in {len(relicensed)} file(s)" if relicensed else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
