# Copyright 2026 Exabeam, Inc.
# SPDX-License-Identifier: Apache-2.0
# GENERATED by gen_identity.py from identity.json — do not edit; CI fails if this drifts.
# Sourced by install.sh and preflight.sh so the identity is read without python3.
SOCXEN_ID_NAME=socxen
SOCXEN_ID_VERSION=0.8.5
SOCXEN_ID_MCP_SERVER=exabeam
SOCXEN_ID_MARKETPLACE_REPO=open-agent-ai-security/plugins
SOCXEN_ID_MARKETPLACE_NAME=open-agent-ai-security
