# Copyright 2026 Exabeam, Inc.
# SPDX-License-Identifier: Apache-2.0
# GENERATED by gen_identity.py from identity.json — do not edit; CI fails if this drifts.
# Sourced by install.sh and preflight.sh so the identity is read without python3.
RAFFKIN_ID_NAME=raffkin
RAFFKIN_ID_VERSION=0.9.0
RAFFKIN_ID_LICENSE=Apache-2.0
RAFFKIN_ID_MCP_SERVER=exabeam
RAFFKIN_ID_MARKETPLACE_REPO=open-agent-ai-security/plugins
RAFFKIN_ID_MARKETPLACE_NAME=open-agent-ai-security
